-- ============================================================
-- Semantic search plumbing
--
-- Adds:
--   1. find_similar_applications(target_id, match_count) RPC.
--   2. request_embedding() trigger function that fires pg_net.http_post
--      to the generate-embedding Edge Function.
--   3. Triggers on insert and on update-of-embedding-inputs that call
--      request_embedding().
--
-- The Edge Function URL and shared secret are read from Supabase Vault
-- at runtime. They are NOT stored in this migration. Populate them
-- out-of-band (one-off, not committed) with:
--   select vault.create_secret('<url>',    'edge_function_url');
--   select vault.create_secret('<secret>', 'edge_function_secret');
--
-- IVFFlat index on embeddings is intentionally deferred until the table
-- has enough rows for cluster centroids to be meaningful. See
-- TrackWise.md §4.5.
-- ============================================================

-- ------------------------------------------------------------
-- RPC: find_similar_applications
-- Returns top N matches by cosine similarity to target_id's embedding.
-- security invoker → RLS on `applications` filters target lookup and
-- the candidate scan to the caller's own rows.
-- ------------------------------------------------------------
create or replace function find_similar_applications(
  target_id uuid,
  match_count int default 5
)
returns table (
  id uuid,
  company text,
  role text,
  similarity float
)
language sql
security invoker
as $$
  select
    a.id,
    a.company,
    a.role,
    (1 - (a.embedding operator(extensions.<=>) target.embedding))::float as similarity
  from applications a
  cross join (
    select embedding
    from applications
    where id = target_id
      and embedding is not null
  ) target
  where a.id <> target_id
    and a.embedding is not null
  order by a.embedding operator(extensions.<=>) target.embedding
  limit match_count;
$$;

-- ------------------------------------------------------------
-- Trigger function: request_embedding
--
-- Fires pg_net.http_post to the generate-embedding Edge Function with
-- the shared secret header. Fire-and-forget: pg_net queues the request
-- asynchronously, so this returns immediately.
--
-- security definer: this function reads from `vault.decrypted_secrets`,
-- which is restricted. The function itself takes no user input — only
-- NEW.id is interpolated, and it is a UUID generated by Postgres — so
-- there is no SQL/header injection surface. The HTTP call goes to a
-- hardcoded (vault-stored) URL.
-- ------------------------------------------------------------
create or replace function request_embedding()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  fn_url    text;
  fn_secret text;
begin
  select decrypted_secret into fn_url
    from vault.decrypted_secrets
    where name = 'edge_function_url';

  select decrypted_secret into fn_secret
    from vault.decrypted_secrets
    where name = 'edge_function_secret';

  if fn_url is null or fn_secret is null then
    raise warning 'request_embedding: vault secrets missing; skipping';
    return new;
  end if;

  perform net.http_post(
    url     := fn_url,
    body    := jsonb_build_object('applicationId', new.id),
    headers := jsonb_build_object(
      'Content-Type',      'application/json',
      'x-internal-secret', fn_secret
    )
  );

  return new;
end;
$$;

-- ------------------------------------------------------------
-- Triggers
-- One after insert; one after update of the columns that feed the
-- embedding input (company, role, notes). Editing other columns
-- (status, location, salary) does NOT re-embed.
-- ------------------------------------------------------------
create trigger on_application_inserted_embed
  after insert on applications
  for each row execute function request_embedding();

create trigger on_application_updated_embed
  after update of company, role, notes on applications
  for each row execute function request_embedding();
